name: Test snakemake ğŸ pipeline
on:
  pull_request:
    branches:
    - main

jobs:
  test-pipeline:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - "8888:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Setup pipeline ğŸš°
        uses: actions/checkout@v4

      - name: Setup slurm ğŸŒ
        uses: koesterlab/setup-slurm-action@v1

      - name: Cache conda ğŸ¦
        uses: actions/cache@v4
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER_CONDA: 1
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER_CONDA }}-${{hashFiles('environment.yml') }}

      - name: Setup conda ğŸ
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: aatrnaseqpipe
          environment-file: environment.yml
          # https://github.com/conda-incubator/setup-miniconda/issues/267
          # XXX don't use this: use-only-tar-bz2: true

      - name: Cache test data ğŸ¦
        uses: actions/cache@v4
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER_TEST_DATA: 0
        with:
          path: ~/.test
          key:
            # hash based on the FASTA reference
            ${{ runner.os }}-test-data-${{ env.CACHE_NUMBER_TEST_DATA }}-${{hashFiles('.test/sacCer3-mature-tRNAs-dual-adapt-v2.fa')}}

      - name: Download test data â¬‡ï¸
        run: |
          echo "::group::Download test data"
          cd .test
          bash download_test_data.sh
          ls -l

          echo "::endgroup::"
